var y=Object.defineProperty;var L=(e,t,r)=>t in e?y(e,t,{enumerable:!0,configurable:!0,writable:!0,value:r}):e[t]=r;var l=(e,t,r)=>(L(e,typeof t!="symbol"?t+"":t,r),r),v=(e,t,r)=>{if(!t.has(e))throw TypeError("Cannot "+r)};var f=(e,t,r)=>(v(e,t,"read from private field"),r?r.call(e):t.get(e)),p=(e,t,r)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,r)};import{S as h,i as m}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const S="https://pixabay.com/",b="api/",q="45229967-0ed54d12f3523f97afd78f48b",w={};var c;class E{constructor(){l(this,"query","");p(this,c,10);l(this,"page",1);l(this,"total_pages",1)}getArticles(){const t=new URLSearchParams({key:q,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=`${S}${b}?${t}`;return console.log(r),fetch(r,w).then(n=>n.json())}get pageSize(){return f(this,c)}}c=new WeakMap;function A(e){return console.log(e),`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
     <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}let $=new h(".gallery a");const g=document.querySelector(".loader");a();const d={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")},i=new E;d.formElem.addEventListener("submit",P);function P(e){if(e.preventDefault(),O(),i.query=e.target.elements.query.value.trim(),i.page=1,d.articleListElem.innerHTML="",i.query.trim()===""){a(),m.error({message:"Info Search input must be filled!"});return}i.getArticles().then(t=>{a(),t.total===0&&m.info({title:"Sorry,",message:"There are no images matching your search query. Please try again!"}),i.totalResult=t.totalResults,j(t.hits)}).catch(t=>{a(),i.totalResult=0,m.error({title:"Error",message:t.message})})}function R(e){return e.map(A).join("")}function j(e){const t=R(e);d.articleListElem.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){g.classList.remove("visually-hidden")}function a(){g.classList.add("visually-hidden")}new h(".gallery a",{captionDelay:250,captionsData:"alt"});
//# sourceMappingURL=commonHelpers.js.map
